// 0 = off
// 1 = warn
// 2 = error

module.exports = {
	rules: {
		// Possible Errors
		'for-direction': 2,
		'getter-return': 2,
		'no-async-promise-executor': 2,
		'no-await-in-loop': 1,
		'no-compare-neg-zero': 2,
		'no-cond-assign': 2,
		'no-console': 0,
		'no-constant-condition': 2,
		'no-control-regex': 2,
		'no-debugger': 2,
		'no-dupe-args': 2,
		'no-dupe-else-if': 2,
		'no-dupe-keys': 2,
		'no-duplicate-case': 2,
		'no-empty': 2,
		'no-empty-character-class': 2,
		'no-ex-assign': 2,
		'no-extra-boolean-cast': 2,
		'no-extra-parens': 0,
		'no-extra-semi': 2,
		'no-func-assign': 2,
		'no-import-assign': 2,
		'no-inner-declarations': 2,
		'no-invalid-regexp': 2,
		'no-irregular-whitespace': 2,
		'no-loss-of-precision': 2,
		'no-misleading-character-class': 2,
		'no-obj-calls': 2,
		'no-promise-executor-return': 2,
		'no-prototype-builtins': 2,
		'no-regex-spaces': 2,
		'no-setter-return': 2,
		'no-sparse-arrays': 2,
		'no-template-curly-in-string': 0,
		'no-unexpected-multiline': 2,
		'no-unreachable': 2,
		'no-unreachable-loop': 0,
		'no-unsafe-finally': 2,
		'no-unsafe-negation': 2,
		'no-unsafe-optional-chaining': 0,
		'no-useless-backreference': 0,
		'require-atomic-updates': 0,
		'use-isnan': 2,
		'valid-typeof': 2,


		// Best Practices
		'accessor-pairs': 0,
		'array-callback-return': 2,
		'block-scoped-var': 2,
		'class-methods-use-this': 2,
		'consistent-return': 2,
		'curly': 2,
		'default-case': 2,
		'default-param-last': 2,
		'dot-notation': 2,
		'eqeqeq': 2,
		'grouped-accessor-pairs': 2,
		'guard-for-in': 1,
		'max-classes-per-file': 0,
		'no-alert': 2,
		'no-caller': 2,
		'no-case-declarations': 2,
		'no-constructor-return': 2,
		'no-div-regex': 2,
		'no-else-return': 2,
		'no-empty-pattern': 2,
		'no-eval': 2,
		'no-extend-native': 2,
		'no-extra-bind': 2,
		'no-extra-label': 2,
		'no-fallthrough': 2,
		'no-floating-decimal': 2,
		'no-global-assign': 2,
		'no-implicit-coercion': 0,
		'no-implicit-globals': 0,
		'no-implied-eval': 2,
		'no-invalid-this': 2,
		'no-iterator': 2,
		'no-labels': 0,
		'no-lone-blocks': 0,
		'no-loop-func': 0,
		'no-magic-numbers': 0,
		'no-multi-spaces': 2,
		'no-multi-str': 2,
		'no-new': 2,
		'no-new-func': 2,
		'no-new-wrappers': 2,
		'no-nonoctal-decimal-escape': 2,
		'no-octal': 2,
		'no-octal-escape': 2,
		'no-param-reassign': 0,
		'no-proto': 2,
		'no-redeclare': 2,
		'no-return-assign': 2,
		'no-return-await': 2,
		'no-script-url': 2,
		'no-self-assign': 2,
		'no-self-compare': 2,
		'no-sequences': 2,
		'no-throw-literal': 2,
		'no-unmodified-loop-condition': 2,
		'no-unused-expressions': 2,
		'no-unused-labels': 2,
		'no-useless-call': 2,
		'no-useless-catch': 2,
		'no-useless-concat': 2,
		'no-useless-escape': 2,
		'no-useless-return': 2,
		'no-void': 2,
		'no-warning-comments': 0,
		'no-with': 2,
		'prefer-named-capture-group': 0,
		'prefer-promise-reject-errors': 2,
		'prefer-regex-literals': 2,
		'radix': 0,
		'require-await': 2,
		'require-unicode-regexp': 2,
		'vars-on-top': 0,
		'wrap-iife': 2,
		'yoda': 2,


		// Variables
		'init-declarations': 0,
		'no-delete-var': 2,
		'no-label-var': 2,
		'no-restricted-globals': [
			2,
			{
				'name': 'event',
				'message': 'Use local parameter instead.'
			},
			{
				'name': 'fdescribe',
				'message': 'Do not commit fdescribe. Use describe instead.'
			}
		],
		'no-shadow': 2,
		'no-shadow-restricted-names': 2,
		'no-undef': 2,
		'no-undef-init': 2,
		'no-undefined': 2,
		'no-unused-vars': 2,
		'no-use-before-define': 2,
	}
};
