module.exports = {
	rules: {
		'array-bracket-newline': [2, 'consistent'],
		'array-bracket-spacing': 2,
		'array-element-newline': [2, 'consistent'],
		'block-spacing': 2,
		'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
		'camelcase': 0,
		'capitalized-comments': 0,
		'comma-dangle': [2, 'always-multiline'],
		'comma-spacing': 2,
		'comma-style': 2,
		'computed-property-spacing': 2,
		'consistent-this': 2,
		'eol-last': 2,
		'func-call-spacing': 2,
		'func-name-matching': 0,
		'func-names': [2, 'as-needed'],
		'func-style': [2, 'declaration', { 'allowArrowFunctions':  true }],
		'function-call-argument-newline': [2, 'consistent'],
		'function-paren-newline': [2, 'multiline'],
		'id-denylist': [2, 'cb', 'callback'],
		'id-length': 0,
		'id-match': 0,
		'implicit-arrow-linebreak': 0,
		'indent': [2, 'tab', {
			'FunctionDeclaration': {
				'parameters': 2,
				'body': 1
			}
		}],
		'jsx-quotes': 0,
		'key-spacing': 2,
		'keyword-spacing': 2,
		'line-comment-position': 0,
		'linebreak-style': 0,
		'lines-around-comment': 0,
		'lines-between-class-members': 2,
		'max-depth': 0,
		'max-len': [2, {
			'code': 80,
			'tabWidth': 4
		}],
		'max-lines': 0,
		'max-lines-per-function': 0,
		'max-nested-callbacks': 0,
		'max-params': 0,
		'max-statements': 0,
		'max-statements-per-line': 2,
		'multiline-comment-style': 0,
		'multiline-ternary': 0,
		'new-cap': 2,
		'new-parens': 2,
		'newline-per-chained-call': 0,
		'no-array-constructor': 2,
		'no-bitwise': 0,
		'no-continue': 0,
		'no-inline-comments': 0,
		'no-lonely-if': 2,
		'no-mixed-operators': 2,
		'no-mixed-spaces-and-tabs': 2,
		'no-multi-assign': 2,
		'no-multiple-empty-lines': 0,
		'no-negated-condition': 0,
		'no-nested-ternary': 0,
		'no-new-object': 2,
		'no-plusplus': 0,
		'no-restricted-syntax': 0,
		'no-tabs': 0,
		'no-ternary': 0,
		'no-trailing-spaces': 2,
		'no-underscore-dangle': 0,
		'no-unneeded-ternary': 0,
		'no-whitespace-before-property': 2,
		'object-curly-newline': [2, { 'consistent': true }],
		'object-curly-spacing': [2, 'always'],
		'object-property-newline': 0,
		'one-var': [2, 'never'],
		'operator-assignment': 2,
		'operator-linebreak': [2, 'after'],
		'padded-blocks': [2, 'never'],
		'padding-line-between-statements': 0,
		'prefer-exponentiation-operator': 2,
		'prefer-object-spread': 2,
		'quote-props': [2, 'consistent'],
		'quotes': [2, 'single', { 'allowTemplateLiterals':  true }],
		'semi': 2,
		'semi-spacing': 2,
		'semi-style': 2,
		'sort-keys': 0,
		'sort-vars': 0,
		'space-before-blocks': 2,
		'space-before-function-paren': [2, {
			'anonymous': 'never',
			'named': 'never',
			'asyncArrow': 'always'
		}],
		'space-in-parens': 2,
		'space-infix-ops': 2,
		'space-unary-ops': [2, {
			'words': true,
			'nonwords': false
		}],
		'spaced-comment': 2,
		'switch-colon-spacing': 2,
		'template-tag-spacing': 2,
		'unicode-bom': 0,
		'wrap-regex': 2,

		// ECMAScript 6
		'arrow-body-style': [2, 'always'],
		'arrow-parens': 2,
		'arrow-spacing': 2,
		'constructor-super': 2,
		'generator-star-spacing': 2,
		'no-class-assign': 2,
		'no-confusing-arrow': 0,
		'no-cond-assign': 2,
		'no-dupe-class-members': 2,
		'no-duplicate-imports': 2,
		'no-new-symbol': 2,
		'no-this-before-super': 2,
		'no-useless-computed-key': 2,
		'no-useless-constructor': 2,
		'no-useless-rename': 2,
		'no-var': 2,
		'object-shorthand': 0,
		'prefer-arrow-callback': 0,
		'prefer-const': 2,
		'prefer-destructuring': 0,
		'prefer-numeric-literals': 2,
		'prefer-rest-params': 2,
		'prefer-spread': 2,
		'prefer-template': 0,
		'require-yield': 2,
		'rest-spread-spacing': 2,
		'sort-imports': 0,
		'symbol-description': 0,
		'template-curly-spacing': 2,
		'yield-star-spacing': [2, 'after']
	}
}
